import { MD3LightTheme as DefaultTheme } from 'react-native-paper';
import { colors } from './colors';

export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: colors.primary,
    primaryContainer: colors.primaryLight,
    secondary: colors.secondary,
    secondaryContainer: colors.secondaryLight,
    tertiary: colors.accent,
    tertiaryContainer: colors.accentLight,
    surface: colors.surface,
    surfaceVariant: colors.background,
    background: colors.background,
    error: colors.error,
    errorContainer: colors.error + '20',
    onPrimary: colors.white,
    onPrimaryContainer: colors.primaryDark,
    onSecondary: colors.white,
    onSecondaryContainer: colors.secondaryDark,
    onTertiary: colors.white,
    onTertiaryContainer: colors.accentDark,
    onSurface: colors.text,
    onSurfaceVariant: colors.textLight,
    onBackground: colors.text,
    onError: colors.white,
    onErrorContainer: colors.error,
    outline: colors.lightGray,
    outlineVariant: colors.lightGray + '80',
    inverseSurface: colors.darkGray,
    inverseOnSurface: colors.white,
    inversePrimary: colors.primaryLight,
    shadow: colors.black,
    scrim: colors.overlay,
    backdrop: colors.overlay,
  },
  // Custom theme properties
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
  },
  borderRadius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    round: 999,
  },
  typography: {
    headlineLarge: {
      fontSize: 32,
      fontWeight: 'bold',
      lineHeight: 40,
    },
    headlineMedium: {
      fontSize: 28,
      fontWeight: 'bold',
      lineHeight: 36,
    },
    headlineSmall: {
      fontSize: 24,
      fontWeight: 'bold',
      lineHeight: 32,
    },
    titleLarge: {
      fontSize: 22,
      fontWeight: '600',
      lineHeight: 28,
    },
    titleMedium: {
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 24,
    },
    titleSmall: {
      fontSize: 14,
      fontWeight: '600',
      lineHeight: 20,
    },
    bodyLarge: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 24,
    },
    bodyMedium: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 20,
    },
    bodySmall: {
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
    },
    labelLarge: {
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
    },
    labelMedium: {
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
    },
    labelSmall: {
      fontSize: 11,
      fontWeight: '500',
      lineHeight: 16,
    },
  },
  elevations: {
    level0: 0,
    level1: 1,
    level2: 3,
    level3: 6,
    level4: 8,
    level5: 12,
  },
}; 